terrestrial:
- arboreal
- arid
- carr
- cave
- cave-entrance
- cave-floor
- city
- cliff
- deciduous-forest
- desert
- desert-oasis
- dust
- evergreen-forest
- flooded-grassland
- forest
- forest-edge
- grassland
- karst
- moor
- mountain
- orchard
- peatland
- savanna
- steppe
- swamp-forest
- terrestrial
- terrestrial-freshwater
- tropical-
- tropical-forest
- tundr
- valley
- woodland
- woodland-canopy
- woodland-clearing
aquatic:
- air-water_interface
- aqu
- aquatic
- aquatic-vegetati
- aquatic-vegetation
- aquifer
- atoll
- backwater
- brackish-water
- coast
- coastal-pl
- coastal-plain
- delta
- estuary
- freshwater-lake
- lagoon
- lake
- marine
- mud
- non-wetland
- pleuston
- pond
- river
- river-island
- river-mouth
- river-valley
- riverbeds
- rivers
- riverscoast
- riversfreshwater
- riverssediment
- saline-lake
- saline-water
- stream-bank
- submerged_vegetation
- temporary-aquatic
- waterfall
- watersurface
- weir
- wetland