CATEGORY_1:
  tag: AUTOTROPH
  requirements:
    - or:
        - diet: autotroph
        - diet: symbiotr
    - and:
        - diet: carnivore
        - kingdom: planta

CATEGORY_2:
  tag: HERBIVORE
  requirements:
    - or:
        - diet: herbivore
        - diet: fruit
        - diet: leaves
        - diet: plant
        - diet: seed
        - diet: alga
        - diet: leaf
        - diet: wood
        - diet: root
        - diet: flower
        - diet: pollen
        - diet: nectar
        - diet: weed
        - diet: lichen
        - diet: nectar
        - diet: fung
        - diet: omniv
        - diet: grass
        - diet: phyto
        - diet: microo
  relations:
    - CATEGORY_1: 1
    - CATEGORY_6: 1

CATEGORY_3:
  tag: CARNIVORE
  requirements:
    - or:
        - diet: carnivore
        - diet: egg
        - diet: vertebr
        - diet: worm
        - diet: insect
        - diet: fish
        - diet: crustacea
        - diet: echino
        - diet: amphibi
        - diet: mollusc
        - diet: mammal
        - diet: bird
        - diet: reptile
        - diet: arthrop
        - diet: zoo
        - diet: omniv
        - diet: predato
        - diet: microo

CATEGORY_4:
  tag: DETRITIVORE
  requirements:
    - or:
        - diet: detrit
        - diet: sedimen
        - diet: mor
        - diet: litter
        - diet: clay
        - diet: suspend
        - diet: filt

CATEGORY_5:
  tag: SCAVENGER
  requirements:
    - or:
        - diet: scaveng
        - diet: carrion
  relations:
    - CATEGORY_2: 1
    - CATEGORY_3: 1
    - CATEGORY_4: 1
    - CATEGORY_5: 1
    - CATEGORY_6: 1
    - CAYEGORY_7: 1

CATEGORY_6:
  tag: PARASITE OF PLANTS
  requirements:
    - and:
        - diet: parasit
        - kingdom: Plantae
  relations:
    - CATEGORY_1: 1

CATEGORY_7:
  tag: PARASITE OF ANIMALS
  requirements:
    - and:
        - diet: parasit
        - kingdom: Animalia
  relations:
    - CATEGORY_2: 3
    - CATEGORY_3: 3
    - CATEGORY_4: 3
    - CATEGORY_5: 3
    - CATEGORY_6: 3
    - CATEGORY_7: 3

CATEGORY_8:
  tag: INSECTIVORE
  requirements:
    - or:
        - diet: insect
        - diet: invert
        - diet: arthrop
  relations:
    - CATEGORY_17: 2

CATEGORY_9:
  tag: MOLLUSCIVORE
  requirements:
    - or:
        - diet: worm
        - diet: invert
        - diet: mollusc
  relations:
    - CATEGORY_18: 2

CATEGORY_10:
  tag: DUROPHAGOUS
  requirements:
    - or:
        - diet: crustac
        - diet: echino
        - diet: invert
  relations:
    - CATEGORY_20: 2

CATEGORY_11:
  tag: PISCIVORE
  requirements:
    - or:
        - diet: fish
  relations:
    - CATEGORY_19: 2

CATEGORY_12:
  tag: RANIVORE
  requirements:
    - or:
        - diet: amphibi
  relations:
    - CATEGORY_21: 2

CATEGORY_13:
  tag: HERPETIVORE
  requirements:
    - or:
        - diet: reptile
  relations:
    - CATEGORY_22: 2

CATEGORY_14:
  tag: BIRDVORE-OOPHAGOUS
  requirements:
    - or:
        - diet: bird
        - diet: egg
  relations:
    - CATEGORY_23: 2

CATEGORY_15:
  tag: MAMMALIVORE
  requirements:
    - or:
        - diet: mammal
  relations:
    - CATEGORY_24: 2

CATEGORY_16:
  tag: GENERALIST
  requirements:
    - or:
        - diet: carnivo
        - diet: omnivor
  relations:
    - CATEGORY_2: 2
    - CATEGORY_3: 2

CATEGORY_17:
  tag: Insects
  requirements:
    - or:
        - type: Insecta

CATEGORY_18:
  tag: Molluscs
  requirements:
    - or:
        - order: Mollusca

CATEGORY_19:
  tag: Fish
  requirements:
    - or:
        - type: Sarcopterygii
        - type: Actinopterygii
        - type: Cephalaspidomorphi

CATEGORY_20:
  tag: Eaten_by_Durophagus
  requirements:
    - or:
        - type: Malacostraca
        - type: Ostracoda
        - order: Echinodermata
        - type: Branchiopoda
        - type: Maxillopoda

CATEGORY_21:
  tag: Amphibian
  requirements:
    - or:
        - type: Amphibia

CATEGORY_22:
  tag: Reptiles
  requirements:
    - or:
        - type: Reptilia

CATEGORY_23:
  tag: Aves
  requirements:
    - or:
        - type: Aves

CATEGORY_24:
  tag: Mammalia
  requirements:
    - or:
        - type: Mammalia
